version: "2.2"
services:
  selenium_hub:
    image: ${DOCKER_REGISTRY}selenium/hub:3.14.0-curium
    ports:
      - 4444:4444

  appium_server:
    image: appium/appium
    depends_on:
      - selenium_hub
    network_mode: "service:selenium_hub"
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ~/.android:/root/.android
      - $PWD/example/sample_apk:/root/tmp
    environment:
      - CONNECT_TO_GRID=true
      - SELENIUM_HOST=selenium_hub
      - RELAXED_SECURITY=true


  nexus_emulator:
    image: ${DOCKER_REGISTRY}budtmo/docker-android-x86-10.0
    privileged: true
    scale: 1
    depends_on:
      - selenium_hub
      - appium_server
    ports:
      - 6080:6080
      - 4723:4723
      - 5554:5554
      - 5555:5555
    volumes:
      - $PWD/example/sample_apk:/root/tmp/sample_apk
      - ./video-nexus_7.1.1:/tmp/video
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - AUTO_RECORD=true