const d1 =  {
    "@burstware/expo-plaid-link": "^1.0.2",
    "@expo-google-fonts/roboto": "^0.1.0",
    "@react-native-async-storage/async-storage": "^1.15.5",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/cli": "^5.0.1",
    "@react-native-community/datetimepicker": "3.0.4",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-picker/picker": "^1.15.0",
    "@react-navigation/bottom-tabs": "^5.11.2",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "axios": "^0.21.0",
    "expo-document-picker": "^8.4.1",
    "expo-file-system": "~9.3.0",
    "expo-font": "~8.4.0",
    "expo-linear-gradient": "^8.4.0",
    "expo-linking": "~2.0.0",
    "expo-local-authentication": "~9.5.0",
    "expo-mail-composer": "~9.0.0",
    "expo-splash-screen": "~0.8.0",
    "expo-status-bar": "~1.0.3",
    "expo-updates": "~0.4.2",
    "expo-web-browser": "~9.2.0",
    "faker": "^5.5.3",
    "form-data": "^2.3.3",
    "mime-types": "^2.1.29",
    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-animate-number": "^0.1.2",
    "react-native-branch": "^5.0.3",
    "react-native-calendar-picker": "^7.0.9",
    "react-native-camera": "^3.44.1",
    "react-native-circular-progress": "^1.3.7",
    "react-native-confetti-cannon": "^1.5.1",
    "react-native-console-time-polyfill": "*",
    "react-native-currency-input": "^0.1.2",
    "react-native-dotenv": "^3.1.1",
    "react-native-dots-pagination": "^0.1.11",
    "react-native-eject": "^0.1.2",
    "react-native-fade": "^2.0.2",
    "react-native-fbsdk": "^3.0.0",
    "react-native-flash-message": "^0.1.17",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-google-places-autocomplete": "^2.1.3",
    "react-native-image-picker": "^3.6.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-offline": "^5.7.0",
    "react-native-onesignal": "^4.1.0",
    "react-native-permissions": "^3.0.3",
    "react-native-picker-select": "^8.0.4",
    "react-native-progress": "^4.1.2",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.0",
    "react-native-searchable-dropdown": "^1.1.3",
    "react-native-sms-verifycode": "^2.4.3",
    "react-native-store-version": "^1.3.1",
    "react-native-svg": "^9.13.6",
    "react-native-svg-animated-linear-gradient": "^0.4.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-swiper": "^1.6.0",
    "react-native-unimodules": "^0.12.0",
    "react-navigation": "^4.4.3",
    "react-navigation-drawer": "^2.7.0",
    "react-navigation-stack": "^2.10.2",
    "react-navigation-tabs": "^2.10.1",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22",
    "smartlook-react-native-wrapper": "^0.40.0",
    "tealium-react-native": "^2.1.1"
  }
const d2 = {
    "@burstware/expo-plaid-link": "^1.0.2",
    "@expo-google-fonts/roboto": "^0.1.0",
    "@react-native-async-storage/async-storage": "^1.15.5",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/datetimepicker": "3.0.4",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-native-picker/picker": "^1.15.0",
    "@react-navigation/bottom-tabs": "^5.11.2",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "axios": "^0.21.0",
    "expo-document-picker": "^8.4.1",
    "expo-file-system": "~9.3.0",
    "expo-font": "~8.4.0",
    "expo-linear-gradient": "^8.4.0",
    "expo-linking": "~2.0.0",
    "expo-local-authentication": "~9.5.0",
    "expo-mail-composer": "~9.0.0",
    "expo-splash-screen": "~0.8.0",
    "expo-status-bar": "~1.0.3",
    "expo-updates": "~0.4.2",
    "expo-web-browser": "~9.2.0",
    "faker": "^5.5.3",
    "form-data": "^2.3.3",
    "mime-types": "^2.1.29",
    "react": "17.0.1",
    "react-dom": "^16.13.1",
    "react-error-boundary": "^3.1.3",
    "react-native": "0.64.2",
    "react-native-animate-number": "^0.1.2",
    "react-native-branch": "^5.0.3",
    "react-native-calendar-picker": "^7.0.9",
    "react-native-camera": "^3.44.1",
    "react-native-circular-progress": "^1.3.7",
    "react-native-confetti-cannon": "^1.5.1",
    "react-native-console-time-polyfill": "*",
    "react-native-currency-input": "^0.1.2",
    "react-native-dotenv": "^3.1.1",
    "react-native-dots-pagination": "^0.1.11",
    "react-native-fade": "^2.0.2",
    "react-native-fbsdk": "^3.0.0",
    "react-native-flash-message": "^0.1.17",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-google-places-autocomplete": "^2.1.3",
    "react-native-image-picker": "^3.6.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-offline": "^5.7.0",
    "react-native-onesignal": "^4.1.0",
    "react-native-permissions": "^3.0.3",
    "react-native-picker-select": "^8.0.4",
    "react-native-plaid-link": "^1.4.4",
    "react-native-progress": "^4.1.2",
    "react-native-qrcode-svg": "^6.0.6",
    "react-native-reanimated": "~1.13.0",
    "react-native-responsive-linechart": "^5.7.1",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.0",
    "react-native-searchable-dropdown": "^1.1.3",
    "react-native-sms-verifycode": "^2.4.3",
    "react-native-store-version": "^1.3.1",
    "react-native-svg": "^9.13.6",
    "react-native-svg-animated-linear-gradient": "^0.4.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-swiper": "^1.6.0",
    "react-native-unimodules": "^0.12.0",
    "react-native-web": "^0.13.12",
    "react-native-webview": "^11.12.0",
    "react-navigation": "^4.4.3",
    "react-navigation-drawer": "^2.7.0",
    "react-navigation-stack": "^2.10.2",
    "react-navigation-tabs": "^2.10.1",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22",
    "smartlook-react-native-wrapper": "^0.40.0",
    "tealium-react-native": "^2.1.0"
  }


function diff(obj1, obj2) {
    const result = {};
    if (Object.is(obj1, obj2)) {
        return undefined;
    }
    if (!obj2 || typeof obj2 !== 'object') {
        return obj2;
    }
    Object.keys(obj1 || {}).concat(Object.keys(obj2 || {})).forEach(key => {
        if(obj2[key] !== obj1[key] && !Object.is(obj1[key], obj2[key])) {
            result[key] = obj2[key];
        }
        if(typeof obj2[key] === 'object' && typeof obj1[key] === 'object') {
            const value = diff(obj1[key], obj2[key]);
            if (value !== undefined) {
                result[key] = value;
            }
        }
    });
    return result;
}

// console.log('d1: ', d1);

console.log('diff(d1, d2): ', diff(d1, d2));
